### ISSUE TITLE
Locale setting through DEFLOCAL not taken in account

### ISSUE THREAD

**Issue by vknecht** [drtyhlpr/rpi2-gen-image#11]
Hello,
the sed expression line 223 must use double quotes for the shell variable substitution to work.
Right now, the /etc/locale.gen is NOT modified by sed.

**Comment by drtyhlpr** [comment]
ups will fix soon / thanks for pointing that out

**Comment by drtyhlpr** [comment]
hanks for all your adds and fixes vknecht -great work - please give me some time to test your PRs

**Comment by drtyhlpr** [comment]
merged your fix ty
