### ISSUE TITLE
sources.list and debootstrap disagree about syntax

### ISSUE THREAD

**Issue by voltagex** [drtyhlpr/rpi2-gen-image#12]
If you run `rpi2-gen-image.sh` with `APT_SERVER=ftp.au.debian.org` (or whatever server), `debootstrap` will fail with `unknown location ftp.debian.org/debian/dists/jessie/Release` because it's expecting a 'http://' in front of the location.

However, later on the `sources.list` is generated from the same variable

```bash
# Set up initial sources.list
cat <<EOM >$R/etc/apt/sources.list
deb http://${APT_SERVER}/debian ${RELEASE} main contrib
#deb-src http://${APT_SERVER}/debian ${RELEASE} main contrib
```

So if you make APT_SERVER correct by adding a http in front of it, you'll end up with an invalid sources.list later

**Comment by drtyhlpr** [comment]
should work now
