### ISSUE TITLE
License inconsistencies

### ISSUE THREAD

**Issue by felgru** [drtyhlpr/rpi2-gen-image#2]
The file LICENSE includes GPL-3 while the header of rpi2-gen-image.sh mentions GPL-2 or later, like the original  rpi2-build-image.sh from Ryan Finnie did.

Was it your intention to make use of the "or later" clause and switch to GPL-3 (or later)? Then I would change the header of rpi2-gen-image.sh accordingly. Otherwise you might replace LICENSE with the GPL-2 which you can get [here](https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt).

**Comment by drtyhlpr** [comment]
I am sorry. I didn't care about LICENSES. I will replace it right now - thanks for the feedback

**Comment by drtyhlpr** [comment]
fixed.

**Comment by drtyhlpr** [comment]
:]
