### ISSUE TITLE
Custom dependencies

### ISSUE THREAD

**Issue by stylesuxx** [drtyhlpr/rpi2-gen-image#20]
Hey,
thank you for your hard work, this is very close to what I am looking for.
Maybe I have missed it in the README, but is there a way to add custom packages during image build?
This are the use cases I am looking for:
* Install custom dependencies during debootstrapping, I want to provide a list of packages from the official repository that are baked into the final image.
* Install custom dependencies from an external reposiory, aka add a custom sources.list file and pull some packages from there.

Those two things should preferably happen through a config file and not by editing the script directly.

If this is not possible yet, but something you would like to see, let me know and I would happily contribute that functionality.

**Comment by drtyhlpr** [comment]
thanks for the fix. some package includes still seem to produce some errors... but well...
