### ISSUE TITLE
Running script in chroot

### ISSUE THREAD

**Issue by stylesuxx** [drtyhlpr/rpi2-gen-image#21]
Hey,
I would like to run one or more script as last step of the image building process, or better said as the last step before the image is actually built.

Is this planned, or would you like to see this feature? If so, I am willing to contribute this functionality.

**Comment by drtyhlpr** [comment]
hi, is this feature integrated #25 (rpi2-gen-image/files/firstboot/) or do you / does it- require to have an ARGV to define a script to put to files/firstboot?

**Comment by stylesuxx** [comment]
It takes a path as an argument, all exectuables in this path will be executed as last step in the bootstrapping process, before the final image is built.

**Comment by drtyhlpr** [comment]
merged you pr, thx!
