### ISSUE TITLE
Apt Proxy

### ISSUE THREAD

**Issue by stylesuxx** [drtyhlpr/rpi2-gen-image#22]
Shouldn't the proxy setting be applied if APT_PROXY is not NULL? **-z**  evaluates to true if the variable is NULL, in this case a string of length 0. In this case I think you should check for not NULL or **-n**

https://github.com/drtyhlpr/rpi2-gen-image/blob/master/rpi2-gen-image.sh#L205

If I set no proxy I get this Error:
```
E: Syntax error /etc/apt/apt.conf.d/10proxy:2: Extra junk at end of file
```

**Comment by drtyhlpr** [comment]
fixed by daniell1 / thanks for the fix / I will work on other issues mentioned.

**Comment by stylesuxx** [comment]
Not sure if this solves the problem, since the check with **-z** is still there. This evaluates to true when the string is empty, so the Proxy is only set when the string is empty...

**Comment by daniell1** [comment]
My fix only fixed the syntax error. I didn't check anything else :)
