### ISSUE TITLE
SOUND_ENABLE not fully working

### ISSUE THREAD

**Issue by drtyhlpr** [drtyhlpr/rpi2-gen-image#3]
1/2 The ENABLE_SOUND was not fully tested and alsa packages are missing - needs some testing - please give me some time.

2/2 The ENABLE_SOUND=false does not work - the *snd* modules are still loaded no matter if they are listed in the modules blacklist file. working on a fix.

**Comment by drtyhlpr** [comment]
hm works with snd_bcm2835. fixed

**Comment by DeeAitch** [comment]
No sound. rpi2

alsamixer
cannot open mixer: No such file or directory

Linux version 4.14.70-v7 (root@notte) (gcc version 6.3.0 20170516 (Debian 6.3.0-18)) #1 SMP Tue Sep 18 00:30:32 CDT 2018

SOUND_ENABLE=true

**Comment by DeeAitch** [comment]
Solved
dtparam=audio=on to /boot/config.txt
