### ISSUE TITLE
Added parameter for building latest rpi2 kernel, needs testing and feedback

### ISSUE THREAD

**Issue by drtyhlpr** [drtyhlpr/rpi2-gen-image#31]
hi, please test the building, hunt down the errors (some in dmsg) and tell me what additional parameters you need. feel free to PR :).

missing:
- KERNEL_CONFIG parameter for user defined kernel config
- ENABLE_INITRAMFS to use initramfs

have fun

**Comment by 459below** [comment]
Hello,

it be very well my Debian system, but I think there could be a problem with "crossbuild-essential-armhf". If I'm not mistaken, that package doesn't exist in Jessie, but only in sid. I've been running sid for a while and building the kernel worked like a charm. Until a few weeks ago. Maybe it was me, maybe it's the package itself.

In any case I have downgraded from sid to testing in which there doesn't seem to be a "crossbuild-essential-armhf" package. Installing "g++-arm-linux-gnueabihf" and "gcc-arm-linux-gnueabihf" while removing the restriction [here](https://github.com/drtyhlpr/rpi2-gen-image/blob/master/rpi2-gen-image.sh#L163) seems to work.
