### ISSUE TITLE
Typo in rpi2-gen-image.sh

### ISSUE THREAD

**Issue by VonOx** [drtyhlpr/rpi2-gen-image#42]
There is a typo in gen script [@ line 110](https://github.com/drtyhlpr/rpi2-gen-image/blob/master/rpi2-gen-image.sh#L110)

ENABLE_REDUCE=${ENABLE_REDUCE:= _**flase**_ }

**Comment by drtyhlpr** [comment]
ups, thanks for the hint. fixed!
