### ISSUE TITLE
Please enable non-free

### ISSUE THREAD

**Issue by gfa** [drtyhlpr/rpi2-gen-image#43]
I hate to ask this, but I use a wifi dongle with my Pi 2 and it needs non-free firmware, please enable it or give a choice (default=no) to enable non-free

thanks

**Comment by drtyhlpr** [comment]
hi, good idea - I will add the feature soon. I am currently working on the strech support but will add this option soon!

**Comment by drtyhlpr** [comment]
doing some final testing and will add feature in a couple of hours (use non-free at debootstrap components and mod apt sources) so you should be happy

**Comment by drtyhlpr** [comment]
ENABLE_NONFREE added. have fun

**Comment by gfa** [comment]
On Wed, Aug 03, 2016 at 05:07:01AM -0700, drtyhlpr wrote:
> ENABLE_NONFREE added. have fun

thanks!
