### ISSUE TITLE
Bad depends for Stretch

### ISSUE THREAD

**Issue by mati75** [drtyhlpr/rpi2-gen-image#44]
Hi,

On build RELEASE=stretch ENABLE_MINBASE=true ENABLE_REDUCE=true ENABLE_MINGPU=true BUILD_KERNEL=true ENABLE_UBOOT=true I have:

`+ chroot_exec apt-get -q -y --force-yes --no-install-recommends install linux-compiler-gcc-4.8-arm g++ make bc
+ LANG=C LC_ALL=C DEBIAN_FRONTEND=noninteractive chroot /home/mati75/rpi2-gen-image/images/stretch/build/chroot apt-get -q -y --force-yes --no-install-recommends install linux-compiler-gcc-4.8-arm g++ make bc
Reading package lists...
Building dependency tree...
E: Unable to locate package linux-compiler-gcc-4.8-arm
E: Couldn't find any package by glob 'linux-compiler-gcc-4.8-arm'
E: Couldn't find any package by regex 'linux-compiler-gcc-4.8-arm'
`
Package in stretch have name linux-compiler-gcc-5-arm.

**Comment by drtyhlpr** [comment]
oh thanks for you feedback - I will check it, so the UBOOT dep gcc is wrong and propaply just needs a new version name.

**Comment by drtyhlpr** [comment]
yes - I need to patch the apt-get package names in 41-uboot amd 42-fbturbo for stretch release. should be fixed soon.

**Comment by drtyhlpr** [comment]
errors on ENABLE_UBOOT, ENABLE_FBTURBO, ENABLE_REDUCE fixed. have fun
